#!/usr/bin/env bash

php -d variables_order=EGPCS artisan config:cache
php -d variables_order=EGPCS artisan event:cache
php -d variables_order=EGPCS artisan route:cache
php -d variables_order=EGPCS artisan view:cache

# TODO: check if we can run a prometheus exporter on a different port
# TODO move it to worker after mobil release

php artisan serve --host=0.0.0.0 --port=8000